### ISSUE TITLE
[Setting] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by ParkSY0919** [34th-SOPKATHON-iOS-TEAM1/iOS#1]
## 🛠 Issue

- 솝커톤 프로젝트 초기 세팅을 진행합니다.

## 📝 To-do

- [x] .gitignore 추가
- [x] Stroyboard 제거
- [x] 라이브러리 의존성 추가
- [x] SceneDelegate 수정
- [x] Pretendard Font 추가
- [x] 사용할 extensions 추가
