### ISSUE TITLE
[🍎style] 시스페이지 전체 UI 만들기

### ISSUE THREAD

**Issue by hooni0918** [34th-SOPKATHON-iOS-TEAM1/iOS#11]
## 🛠 Issue
시소페이지 UI 구현

## 📝 To-do

- [x] 시소페이지 0번째 이미지뷰 구현
- [x] 이미지뷰 아래 최종목표 섹션구현
- [x] 투두 낫투두 섹션 구현
