### ISSUE TITLE
[FEAT] 온보딩 뷰 UI 구현

### ISSUE THREAD

**Issue by seuriseuljjeok** [34th-SOPKATHON-iOS-TEAM1/iOS#14]
## 🛠 Issue

온보딩 뷰 UI 구현

## 📝 To-do

- [x] 서비스 설명 그래픽 이미지 구현
- [x] 목표 세팅 구현
- [x] 시작 버튼 구현
