### ISSUE TITLE
[FEAT] 온보딩 & 스플래시 GUI 적용

### ISSUE THREAD

**Issue by seuriseuljjeok** [34th-SOPKATHON-iOS-TEAM1/iOS#19]
## 🛠 Issue

온보딩 & 스플래시 GUI 적용

## 📝 To-do

- [x] 온보딩 GUI 적용
- [x] 스플래시 GUI 적용
- [x] 텍스트 필드 설정
