### ISSUE TITLE
[NETWORK] 서버통신

### ISSUE THREAD

**Issue by seuriseuljjeok** [34th-SOPKATHON-iOS-TEAM1/iOS#45]
## 🛠 Issue

서버통신

## 📝 To-do

- [x] 목표 등록 서버통신
- [x] 투두 등록 서버통신
- [x] 낫투두 등록 서버통신
- [x] 등록 투두 조회 서버통신
